import React from "react";
import { AdminReport } from "./admin/AdminReport";
import { AutogeneratedForm } from "./autogenerated-forms/AutogeneratedForm";
import MalDataApprovalStatusReport from "./mal-data-approval/MalDataApprovalReport";
import { NHWADataApprovalStatusReport } from "./nhwa-approval-status/NHWADataApprovalStatusReport";
import { NHWACommentsReport } from "./nhwa-comments/NHWACommentsReport";
import { getVariant } from "./variants";

const widget = getVariant();

const Component: React.FC = () => {
    switch (widget) {
        case "nhwa-comments": {
            return <NHWACommentsReport />;
        }
        case "nhwa-approval-status": {
            return <NHWADataApprovalStatusReport />;
        }
        case "mal-approval-status": {
            return <MalDataApprovalStatusReport />;
        }
        case "admin": {
            return <AdminReport />;
        }
        case "autogenerated-forms": {
            return <AutogeneratedForm />;
        }
    }
};

function Reports() {
    return <Component />;
}

export default Reports;
