import React, { useCallback, useEffect, useState } from "react";
import { useAppContext } from "../../contexts/app-context";

import { DataForm } from "../../../domain/common/entities/DataForm";
import { DataValue, DataValueStore, Period } from "../../../domain/common/entities/DataValue";
import { useDataEntrySelector } from "./useDataEntrySelector";
import i18n from "@eyeseetea/d2-ui-components/locales";
import TableForm from "./TableForm";
import { Maybe } from "../../../utils/ts-utils";
import { Id } from "../../../domain/common/entities/Base";

/*
 * Convert data forms into table, using "-" as a separator. An example:
 *
 *    - ITNs - Basic - Written Policy
 *    - ITNs - Basic - Policy Implemented
 *    - ITNs - Extended - Written Policy
 *    - ITNs - Extended - Policy Implemented
 *
 *    This will create this table:
 *
 *    ITNs            | Written Policy | Policy Implemented |
 *    ITNs - Basic    |                |                    |
 *    ITNs - Extended |                |                    |
 **/

const AutogeneratedForm: React.FC = () => {
    const dataFormInfo = useDataFormInfo();
    if (!dataFormInfo) return <div>{i18n.t("Loading...")}</div>;
    const { dataForm } = dataFormInfo.metadata;

    return (
        <div ref={dataFormInfo.initForm}>
            <CommentDialogStyles />
            <div dangerouslySetInnerHTML={{ __html: dataForm.texts.header }} />
            <TableForm dataFormInfo={dataFormInfo} />
            <div dangerouslySetInnerHTML={{ __html: dataForm.texts.footer }} />
        </div>
    );
};

function useDataFormInfo(): Maybe<DataFormInfo> {
    const { compositionRoot } = useAppContext();
    const { orgUnitId, period, dataSetId, reloadKey, initForm } = useDataEntrySelector();
    const [dataForm, setDataForm] = useState<DataForm>();
    const [dataValues, setDataValues] = useState<DataValueStore>({});

    const { config } = useAppContext();

    const defaultCategoryOptionComboId = config.categoryOptionCombos.default.id;

    useEffect(() => {
        compositionRoot.dataForms.get(dataSetId).then(setDataForm);
    }, [compositionRoot, dataSetId]);

    useEffect(() => {
        compositionRoot.dataForms.getValues(dataSetId, { orgUnitId, period }).then(setDataValues);
    }, [compositionRoot, orgUnitId, dataSetId, period, reloadKey]);

    const saveDataValue = useCallback(
        (dataValue: DataValue) => compositionRoot.dataForms.saveValue(dataValue),
        [compositionRoot]
    );

    return dataForm && dataValues
        ? {
              metadata: { dataForm },
              data: { values: dataValues, save: saveDataValue },
              initForm,
              orgUnitId,
              period,
              categoryOptionComboId: defaultCategoryOptionComboId,
          }
        : undefined;
}

export interface DataFormInfo {
    metadata: { dataForm: DataForm };
    data: {
        values: DataValueStore;
        save: (dataValue: DataValue) => Promise<void>;
    };
    initForm: () => void;
    categoryOptionComboId: Id;
    orgUnitId: Id;
    period: Period;
}

const commentDialogCss = `
    [aria-describedby="historyDiv"] {
        top: 65px !important;
    }
`;

const CommentDialogStyles: React.FC = () => {
    return <style dangerouslySetInnerHTML={{ __html: commentDialogCss }} />;
};

export default React.memo(AutogeneratedForm);
